### ISSUE TITLE
Update from 0.2.5 to 3.32 deletes codes and restoring backup doesn't fully work

### ISSUE THREAD

**Issue by alexpattyn** [flathub/com.github.bilelmoussaoui.Authenticator#15]
# Issue

With the update from 0.2.5 to 3.32 from flathub the codes that were previously there disappear and if you restore from a backup that was made by 0.2.5 not all the codes reappear. I can confirm that they exist in the plain-text backup.

This would most likely upset a lot of people who don't have backups and are surprised when Gnome Software automatically updates their app.  For now I've disabled auto updates and luckily I had two computers with my codes.

**Comment by bilelmoussaoui** [comment]
I'm sorry you had this issue :/  The reason that some of these accounts doesn't re-appear is that your keyring still contains the tokens from the old accounts. What you can do is to open seahorse and search for authenticator and remove all the tokens stored on it and re-importe your plain-text backup.

**Comment by alexpattyn** [comment]
Thanks, I'll try that out. I just figured others would probably have issues.  It came with a warning that permissions changed, so I am not sure if Gnome Software will auto update? So it may be good to put a warning in the change log that their codes should be backed up first.

**Comment by bilelmoussaoui** [comment]
Well, it's already the case https://flathub.org/apps/details/com.github.bilelmoussaoui.Authenticator "Please backup your accounts before updating to the latest version and restore the data after update."

**Comment by alexpattyn** [comment]
Ahh, seems like I over looked that. My bad.

**Comment by alexpattyn** [comment]
So I just deleted everything with the prefix OTP in seahorse and everything under ~/.var/com.github.bilelmoussaoui.Authenticator. From there I restored my codes from a plain-text json file and I am still missing some codes. I am using the version of seahorse from flathub if that makes a difference.

**Comment by bilelmoussaoui** [comment]
Can you reach me on Matrix @bil.elmoussaoui:matrix.org, this way I can guide you to restore your data?

**Comment by fbruetting** [comment]
This also bit me. I received no warning and now all keys are gone…?! WTF

It was updated either by Auto-Updating or CLI, don’t know exactly.

**Comment by bilelmoussaoui** [comment]
@fbruetting No, your keys are not gone at all. They are still stored on the old database. Can you reach me in Matrix to guide how you can recover these?

**Comment by fbruetting** [comment]
Ah, glad! Yes, I can. But I assume more people would follow, so some general info would be cool. :/

**Comment by bilelmoussaoui** [comment]
I have made a snippet here with a code that extracts your old data and give you a backup file you can use later to restore your accounts after the update. 
Follow the steps here https://gitlab.gnome.org/World/Authenticator/snippets/772
and ping on Matrix if you have any issues.

**Comment by bilelmoussaoui** [comment]
No need to follow anything after the update that should land in a few minutes. Things should be restored automatically for the users no matter if you have not updated yet or already updated your app.

**Comment by alexpattyn** [comment]
Hey again @bilelmoussaoui. So I updated to the lasted version from flathub on my one computer and everything seems to be working fine. Then when I try to import the backup on a different computer using a backup from v0.2.5 and from v3.32.1 I get the following error...

```
$ flatpak run com.github.bilelmoussaoui.Authenticator 
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/Authenticator/application.py", line 232, in __on_import_json
    BackupJSON.import_file(filename)
  File "/app/lib/python3.7/site-packages/Authenticator/models/backup.py", line 76, in import_file
    Backup.import_accounts(json.loads(accounts))
  File "/app/lib/python3.7/site-packages/Authenticator/models/backup.py", line 32, in import_accounts
    from ..widgets.accounts import AccountsWidget
ImportError: cannot import name 'AccountsWidget' from 'Authenticator.widgets.accounts' (unknown location)

```

**Comment by alexpattyn** [comment]
I thought it may be an issue with where it was reading from (a USB device) so I copied it to my ~/Downloads folder and had the same issue. I also uninstalled and deleted everything in ~/.var/.../com.github.bilelmoussaoui.Authenticator and then reinstalled with no luck either.
