### ISSUE TITLE
Codes missing on upgrade [Specific to Fedora 32 beta?]

### ISSUE THREAD

**Issue by alexpattyn** [flathub/com.github.bilelmoussaoui.Authenticator#19]
So I thought it was an issue with authenticator just not displaying the codes...

![image](https://user-images.githubusercontent.com/28536677/77284725-b62c9480-6ca5-11ea-90e3-09319b664700.png)

But it seems that when upgrading from Fedora 31 ro 32 beta (on silverblue) all of the codes have been erased. I am guessing that is the case, since when I go to backup the codes, it just produces an empty json file. 

I can't image it was a fedora issue, since ideally the flatpak shouldn't be affected by the base install. Will look into this issue further.

**Comment by alexpattyn** [comment]
So after rolling back to fedora 31 it seems my data is still there. So in Fedora 32 beta...

```
$ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree://fedora:fedora/32/x86_64/silverblue
                   Version: 32.20200319.n.0 (2020-03-19T08:25:20Z)
                BaseCommit: c1eee0a18bef026b066d04392773550141e2121329ee75da88f190b2b622fb53
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
           LayeredPackages: gnome-tweak-tool
```

It seems all of the data isn't loaded? Since as I said in f32 I can't see the codes and the backup json files are empty, specifically "[]", while if I rollback to f31 they seem to be back again and I can make a proper backup json file. So I am not sure if this is a weird issue with Gnome 3.36 or something in the f32 beta.

**Comment by bilelmoussaoui** [comment]
It seems gnome-keyring-daemon crashes very often on f32 beta. Please re-run it with gnome-keyring-daemon --replace. 
You should also unlock the keyring manually once you have done that using something like Seahorse as the app doesn't unlock it itself if needed in the current version.

**Comment by bilelmoussaoui** [comment]
Anyway, this is unrelated to the flatpak package & the app itself. Closing

**Comment by alexpattyn** [comment]
```
$ gnome-keyring-daemon --replace
** Message: 10:19:02.427: Replacing daemon, using directory: /run/user/1000/keyring
GNOME_KEYRING_CONTROL=/run/user/1000/keyring
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
```

Still can't see anything in Authenticator after running the above command, but I can see my passwords in Seahorse. Either way I agree this is a Fedora issue since rolling back showed that everything is there still.

**Comment by bilelmoussaoui** [comment]
I will probably ask for help in Fedora forums and see where that leads you to. Or open a bug report in bugzilla

**Comment by alexpattyn** [comment]
Just as an FYI for any one looking at this issue in the future deleting `~/.var/app/com.github.bilelmoussaoui.Authenticator` and then re-importing the 2FA codes worked. So not sure what the issue was at the end of the day. 

**Be sure to backup/export your codes to a \*.json file first.**

**Comment by bilelmoussaoui** [comment]
It seems the secrets are now sandboxed, that's why Authenticator fails to retrieve the old tokens as it can't access the secrets stored outside of the sandbox, except we had no way to migrate this data :(

**Comment by alexpattyn** [comment]
Thats fine. I am glad holes in the sandbox are slowly being filled :)

I do want to add that for users of Fedora Silverblue that you should:

1. Rollback to 31 from 32.
2. Open authenticator > backup > plain text json (check that your codes are in the json file just to be safe)
3. Go back to 32 
4. Delete `~/.var/app/com.github.bilelmoussaoui.Authenticator`
5. Restore the backup you made and you should be all set. 

**Be careful if Authenticator is your only way to access your 2FA codes, you should always have a backup, etc.**
