### ISSUE TITLE
Version 3.32.2 fails to start

### ISSUE THREAD

**Issue by bayonne** [flathub/com.github.bilelmoussaoui.Authenticator#22]
Hello,

On Ubuntu 18.04, flatpak 1.8.0, `flatpak run com.github.bilelmoussaoui.Authenticator` yields:

> Traceback (most recent call last):
>   File "/app/lib/python3.7/site-packages/Authenticator/application.py", line 202, in _is_locked_changed
>     Window.get_default().view = WindowView.LOCKED
>   File "/app/lib/python3.7/site-packages/Authenticator/widgets/window.py", line 70, in get_default
>     Window.instance = Window()
>   File "/app/lib/python3.7/site-packages/Authenticator/widgets/window.py", line 55, in __init__
>     self.init_template('Window')
> TypeError: <lambda>() takes 0 positional arguments but 1 was given
> Traceback (most recent call last):
>   File "/app/lib/python3.7/site-packages/Authenticator/application.py", line 77, in do_activate
>     window = Window.get_default()
>   File "/app/lib/python3.7/site-packages/Authenticator/widgets/window.py", line 70, in get_default
>     Window.instance = Window()
>   File "/app/lib/python3.7/site-packages/Authenticator/widgets/window.py", line 55, in __init__
>     self.init_template('Window')
> TypeError: <lambda>() takes 0 positional arguments but 1 was given
>

**Comment by bilelmoussaoui** [comment]
I have reverted the latest runtime update, will do a release later
