### ISSUE TITLE
Update/Upgrade GNOME runtime

### ISSUE THREAD

**Issue by x80486** [flathub/com.github.bilelmoussaoui.Authenticator#23]
I saw one Pull Request to use version `3.36` and then a revert. I would assume there were issues once using the new runtime, but some time has passed since, so if `Authenticator` is ready to upgrade would be nice!

Placing this ticket just to keep track of it :footprints:

**Comment by bilelmoussaoui** [comment]
I'm rewriting it slowly, but surely. I will release it as soon as it's ready.

**Comment by bilelmoussaoui** [comment]
New release is out! https://github.com/flathub/flathub/pull/2095 (or should be there soon)
