### ISSUE TITLE
When adding a new account, pressing the Scan QR code button crashes the gnome-shell wayland session

### ISSUE THREAD

**Issue by Saroufim** [flathub/com.github.bilelmoussaoui.Authenticator#3]
Pressing on "Scan QR Code" always crashes the gnome-session on Wayland. I'm running a fully updated Fedora 27. I'm pretty sure that no matter what goes wrong, a flatpak app should not be able to crash the whole session. This makes me assume that it could be a bug in flatpak or Wayland themselves but I figured I'd get confirmation from you first.

**Comment by bilelmoussaoui** [comment]
Issues should be reported here: https://github.com/bilelmoussaoui/Authenticator/
The issue was already reported: https://github.com/bilelmoussaoui/Authenticator/issues/50
